name: caligo

channels:
  - conda-forge

dependencies:
  - python=3.11

  # Core scientific stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - astropy
  - pyyaml

  # Main science dependencies
  - photochem
  - picaso
  - virga-exo
  - miepython

  # Notebook and testing tools
  - ipykernel
  - pytest

  # Needed for editable package install
  - pip