"""
Caligo optical post-processing utilities.

This module connects a finished Caligo haze-microphysics run to PICASO
without forcing the particles onto a narrow VIRGA .mieff radius grid.

Main idea
---------
Caligo already knows the particle sizes and number densities. The optical
post-processing should therefore calculate optical properties on the Caligo
particle grid itself, then format the resulting layer optical depths for
PICASO.

Current modes
-------------
compact_mie
    Spherical Mie calculation using the compact-equivalent Caligo radius.
    This is the recommended baseline.

aggregate_effective_mie
    Experimental porous-sphere approximation. The aggregate radius and
    effective density from the Caligo context are used to estimate a filling
    factor, then a Maxwell-Garnett effective refractive index is used in a
    Mie calculation. This is not a full fractal-aggregate scattering model.

aggregate_table
    Placeholder for a future table generated by a true aggregate scattering
    method such as multi-sphere T-matrix or DDA.

Dependencies
------------
Requires numpy and pandas. Direct Mie calculations require miepython.
Install with, for example:

    conda install -c conda-forge miepython

or

    pip install miepython
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import warnings

import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Small utilities
# -----------------------------------------------------------------------------


def safe_log10(x: Any) -> np.ndarray:
    """Return log10(x) with a tiny positive floor."""
    return np.log10(np.maximum(np.asarray(x, dtype=float), 1e-300))


def _as_array_1d(values: Any, name: str) -> np.ndarray:
    """Convert an input to a finite 1D float array."""
    arr = np.asarray(values, dtype=float)

    if arr.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional. Got shape {arr.shape}.")

    if arr.size == 0:
        raise ValueError(f"{name} is empty.")

    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{name} contains non-finite values.")

    return arr


def _faces_from_centers_ascending(x_center: np.ndarray) -> np.ndarray:
    """Build interval faces from ascending cell centers."""
    x_center = _as_array_1d(x_center, "x_center")

    if x_center.size < 2:
        dx = max(abs(float(x_center[0])) * 0.05, 0.05)
        return np.array([x_center[0] - dx, x_center[0] + dx], dtype=float)

    if not np.all(np.diff(x_center) > 0):
        raise ValueError("x_center must be strictly increasing.")

    faces = np.empty(x_center.size + 1, dtype=float)
    faces[1:-1] = 0.5 * (x_center[:-1] + x_center[1:])
    faces[0] = x_center[0] - 0.5 * (x_center[1] - x_center[0])
    faces[-1] = x_center[-1] + 0.5 * (x_center[-1] - x_center[-2])

    return faces


# -----------------------------------------------------------------------------
# Refractive-index reader
# -----------------------------------------------------------------------------


@dataclass
class RefractiveIndexTable:
    """Container for wavelength-dependent complex refractive indices."""

    wavelength_um: np.ndarray
    n: np.ndarray
    k: np.ndarray
    source: str
    mapping: str
    wave_unit: str

    @property
    def m_complex(self) -> np.ndarray:
        return self.n + 1j * self.k


def _load_numeric_table(path: str | Path) -> np.ndarray:
    """
    Load rows containing at least three numeric values.

    This deliberately ignores header/comment text and keeps only numeric rows,
    which makes it tolerant of several refractive-index table styles.
    """
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"Could not find refractive-index file: {path}")

    rows: list[list[float]] = []

    with path.open("r") as handle:
        for line in handle:
            stripped = line.strip()

            if not stripped:
                continue

            if stripped.startswith(("#", "!", "%")):
                continue

            # Make comma-separated files work too.
            tokens = stripped.replace(",", " ").split()
            values: list[float] = []

            for token in tokens:
                try:
                    values.append(float(token))
                except ValueError:
                    pass

            if len(values) >= 3:
                rows.append(values)

    if not rows:
        raise ValueError(f"No numeric rows were found in {path}.")

    ncols = max(len(row) for row in rows)
    table = np.full((len(rows), ncols), np.nan, dtype=float)

    for i, row in enumerate(rows):
        table[i, : len(row)] = row

    return table


def _convert_wave_to_um(wave: np.ndarray, unit: str) -> np.ndarray:
    """Convert a wavelength array to microns."""
    unit_clean = unit.lower().strip()

    if unit_clean in {"um", "micron", "microns", "micrometer", "micrometers"}:
        return wave.copy()

    if unit_clean in {"nm", "nanometer", "nanometers"}:
        return wave * 1e-3

    if unit_clean in {"angstrom", "angstroms", "a"}:
        return wave * 1e-4

    raise ValueError(
        "wave_unit must be 'micron', 'nanometer', 'angstrom', or 'auto'."
    )


def _score_refrind_candidate(wave_um: np.ndarray, n: np.ndarray, k: np.ndarray) -> float:
    """Score a possible refractive-index column/unit interpretation."""
    good = np.isfinite(wave_um) & np.isfinite(n) & np.isfinite(k)
    good &= wave_um > 0
    good &= n > 0
    good &= k >= 0

    if np.sum(good) < 3:
        return -1e9

    wave = wave_um[good]
    n_good = n[good]
    k_good = k[good]

    order = np.argsort(wave)
    wave = wave[order]
    n_good = n_good[order]
    k_good = k_good[order]

    unique_wave = np.unique(wave)

    if unique_wave.size < 3:
        return -1e9

    score = 0.0

    # Reasonable refractive-index values.
    if 0.5 <= np.nanmedian(n_good) <= 5.0:
        score += 20.0
    else:
        score -= 40.0

    if np.nanmin(k_good) >= 0.0 and np.nanmedian(k_good) <= 10.0:
        score += 15.0
    else:
        score -= 40.0

    # A useful wavelength range for planetary spectra.
    wave_min = float(np.nanmin(wave))
    wave_max = float(np.nanmax(wave))

    if 1e-3 <= wave_min < wave_max <= 1e4:
        score += 10.0

    if wave_min < 30.0 and wave_max > 0.1:
        score += 20.0

    if wave_min <= 0.5 and wave_max >= 5.0:
        score += 10.0

    # Prefer mostly sorted wavelength columns.
    diffs = np.diff(wave)
    if np.all(diffs > 0):
        score += 10.0

    score += min(float(unique_wave.size), 100.0) / 10.0

    return score


def read_refractive_index_file(
    path: str | Path,
    mapping: str = "auto",
    wave_unit: str = "auto",
    verbose: bool = True,
) -> RefractiveIndexTable:
    """
    Read a refractive-index file and infer wavelength, n, and k columns.

    Parameters
    ----------
    path
        Path to a refractive-index file. Common VIRGA-style .refrind tables
        are supported.
    mapping
        Either 'auto', 'col1_wave_col2_n_col3_k', or
        'col0_wave_col1_n_col2_k'. The first option is useful for files where
        column 0 is an index and columns 1, 2, 3 are wavelength, n, k.
    wave_unit
        'auto', 'micron', 'nanometer', or 'angstrom'.
    verbose
        Print the selected mapping.
    """
    path = Path(path)
    table = _load_numeric_table(path)

    candidates: list[tuple[float, str, str, np.ndarray, np.ndarray, np.ndarray]] = []

    mapping_specs: list[tuple[str, int, int, int]] = []

    if mapping == "auto":
        if table.shape[1] >= 4:
            mapping_specs.append(("col1_wave_col2_n_col3_k", 1, 2, 3))
        if table.shape[1] >= 3:
            mapping_specs.append(("col0_wave_col1_n_col2_k", 0, 1, 2))
    elif mapping == "col1_wave_col2_n_col3_k":
        mapping_specs.append((mapping, 1, 2, 3))
    elif mapping == "col0_wave_col1_n_col2_k":
        mapping_specs.append((mapping, 0, 1, 2))
    else:
        raise ValueError(
            "mapping must be 'auto', 'col1_wave_col2_n_col3_k', "
            "or 'col0_wave_col1_n_col2_k'."
        )

    unit_specs: list[str]

    if wave_unit == "auto":
        unit_specs = ["micron", "nanometer", "angstrom"]
    else:
        unit_specs = [wave_unit]

    for map_name, i_wave, i_n, i_k in mapping_specs:
        if max(i_wave, i_n, i_k) >= table.shape[1]:
            continue

        raw_wave = np.asarray(table[:, i_wave], dtype=float)
        n = np.asarray(table[:, i_n], dtype=float)
        k = np.asarray(table[:, i_k], dtype=float)

        for unit in unit_specs:
            wave_um = _convert_wave_to_um(raw_wave, unit)
            score = _score_refrind_candidate(wave_um, n, k)
            candidates.append((score, map_name, unit, wave_um, n, k))

    if not candidates:
        raise ValueError(f"Could not interpret refractive-index table: {path}")

    candidates.sort(key=lambda item: item[0], reverse=True)
    best_score, best_mapping, best_unit, wave_um, n, k = candidates[0]

    if best_score < 0:
        raise ValueError(
            "Could not find a plausible wavelength/n/k mapping for "
            f"{path}. Best candidate score was {best_score:.2f}."
        )

    good = np.isfinite(wave_um) & np.isfinite(n) & np.isfinite(k)
    good &= wave_um > 0
    good &= n > 0
    good &= k >= 0

    wave_um = wave_um[good]
    n = n[good]
    k = k[good]

    order = np.argsort(wave_um)
    wave_um = wave_um[order]
    n = n[order]
    k = k[order]

    unique_wave, unique_indices = np.unique(wave_um, return_index=True)
    wave_um = unique_wave
    n = n[unique_indices]
    k = k[unique_indices]

    if wave_um.size < 3:
        raise ValueError(
            "The selected refractive-index table has fewer than three unique "
            "wavelength points."
        )

    if verbose:
        print("Selected refractive-index mapping:", best_mapping)
        print("Selected wavelength unit:", best_unit)
        print("Wavelength range [um]:", float(wave_um.min()), "to", float(wave_um.max()))
        print("n range:", float(n.min()), "to", float(n.max()))
        print("k range:", float(k.min()), "to", float(k.max()))

    return RefractiveIndexTable(
        wavelength_um=wave_um,
        n=n,
        k=k,
        source=str(path),
        mapping=best_mapping,
        wave_unit=best_unit,
    )


def interpolate_refractive_index(
    refrind: RefractiveIndexTable,
    wavelength_um: np.ndarray,
    extrapolate: str = "clamp",
) -> tuple[np.ndarray, dict[str, Any]]:
    """
    Interpolate a refractive-index table onto a wavelength grid.

    Interpolation is done in log-wavelength space. By default, values outside
    the refractive-index table are clamped to the nearest table edge and a
    diagnostic is returned.
    """
    wavelength_um = _as_array_1d(wavelength_um, "wavelength_um")

    if not np.all(wavelength_um > 0):
        raise ValueError("wavelength_um must be positive.")

    wave_tab = refrind.wavelength_um
    log_wave_tab = safe_log10(wave_tab)
    log_wave = safe_log10(wavelength_um)

    outside_low = wavelength_um < wave_tab.min()
    outside_high = wavelength_um > wave_tab.max()
    outside = outside_low | outside_high

    if np.any(outside) and extrapolate == "raise":
        raise ValueError(
            "Requested wavelengths extend outside the refractive-index table: "
            f"requested [{wavelength_um.min():.3e}, {wavelength_um.max():.3e}] um, "
            f"table [{wave_tab.min():.3e}, {wave_tab.max():.3e}] um."
        )

    if extrapolate not in {"clamp", "raise"}:
        raise ValueError("extrapolate must be 'clamp' or 'raise'.")

    n_interp = np.interp(log_wave, log_wave_tab, refrind.n)
    k_interp = np.interp(log_wave, log_wave_tab, refrind.k)

    diag = {
        "refractive_index_source": refrind.source,
        "refractive_index_mapping": refrind.mapping,
        "refractive_index_wave_unit": refrind.wave_unit,
        "refractive_index_wave_min_um": float(wave_tab.min()),
        "refractive_index_wave_max_um": float(wave_tab.max()),
        "requested_wave_min_um": float(wavelength_um.min()),
        "requested_wave_max_um": float(wavelength_um.max()),
        "n_wavelength_outside_refrind": int(np.sum(outside)),
        "fraction_wavelength_outside_refrind": float(np.mean(outside)),
    }

    return n_interp + 1j * k_interp, diag


# -----------------------------------------------------------------------------
# Mie calculation
# -----------------------------------------------------------------------------


def _import_miepython():
    try:
        import miepython  # type: ignore
    except Exception as exc:  # pragma: no cover
        raise ImportError(
            "Direct Mie calculations require miepython. Install it with "
            "'conda install -c conda-forge miepython' or 'pip install miepython'."
        ) from exc

    return miepython


def _mie_efficiencies_one(m_complex: complex, radius_um: float, wavelength_um: float) -> tuple[float, float, float]:
    """
    Return Qext, Qsca, and asymmetry parameter g for one sphere.

    This wrapper supports several miepython API versions.
    """
    miepython = _import_miepython()

    radius_um = float(radius_um)
    wavelength_um = float(wavelength_um)

    if radius_um <= 0 or wavelength_um <= 0:
        raise ValueError("radius_um and wavelength_um must be positive.")

    x = 2.0 * np.pi * radius_um / wavelength_um

    if hasattr(miepython, "efficiencies_mx"):
        out = miepython.efficiencies_mx(m_complex, x)
        qext, qsca, _qback, g = out[:4]
        return float(qext), float(qsca), float(g)

    if hasattr(miepython, "efficiencies"):
        # Newer miepython versions use diameter and wavelength in the same units.
        diameter_um = 2.0 * radius_um
        out = miepython.efficiencies(m_complex, diameter_um, wavelength_um)
        qext, qsca, _qback, g = out[:4]
        return float(qext), float(qsca), float(g)

    if hasattr(miepython, "mie"):
        out = miepython.mie(m_complex, x)
        qext, qsca, _qback, g = out[:4]
        return float(qext), float(qsca), float(g)

    raise AttributeError(
        "Could not find a supported Mie-efficiency function in miepython."
    )


def _maxwell_garnett_effective_index(m_solid: np.ndarray, filling_factor: np.ndarray) -> np.ndarray:
    """
    Maxwell-Garnett effective refractive index for solid inclusions in vacuum.

    This is an approximate porous-sphere treatment. It is useful for a first
    aggregate sensitivity test, but it is not a replacement for true fractal
    aggregate optics.
    """
    m_solid = np.asarray(m_solid, dtype=complex)
    filling_factor = np.asarray(filling_factor, dtype=float)
    filling_factor = np.clip(filling_factor, 0.0, 1.0)

    eps_i = m_solid**2
    eps_m = 1.0 + 0.0j

    numerator = eps_i + 2.0 * eps_m + 2.0 * filling_factor * (eps_i - eps_m)
    denominator = eps_i + 2.0 * eps_m - filling_factor * (eps_i - eps_m)
    eps_eff = eps_m * numerator / denominator

    return np.sqrt(eps_eff)


def _select_radius_matrix_cm(ctx: dict[str, Any], optics_mode: str) -> np.ndarray:
    """Return a radius matrix with shape (nz, n_bin) in cm."""
    nz = int(ctx["nz"])
    n_bin = int(ctx["n_bin"])

    r_compact_cm = np.asarray(ctx["r_compact_cm"], dtype=float)

    if r_compact_cm.shape != (n_bin,):
        raise ValueError("ctx['r_compact_cm'] must have shape (n_bin,).")

    if optics_mode == "compact_mie":
        return np.repeat(r_compact_cm[None, :], nz, axis=0)

    if optics_mode == "aggregate_effective_mie":
        if "r_fractal_layer_cm" not in ctx:
            raise KeyError(
                "aggregate_effective_mie requires ctx['r_fractal_layer_cm']."
            )

        r_fractal = np.asarray(ctx["r_fractal_layer_cm"], dtype=float)

        if r_fractal.shape != (nz, n_bin):
            raise ValueError(
                "ctx['r_fractal_layer_cm'] must have shape (nz, n_bin)."
            )

        can_be_aggregate = np.asarray(
            ctx.get("can_be_aggregate", np.zeros(n_bin, dtype=bool)),
            dtype=bool,
        )

        w_agg_layer = np.asarray(ctx.get("w_agg_layer", np.zeros(nz)), dtype=float)
        w_agg_matrix = np.clip(w_agg_layer[:, None], 0.0, 1.0) * can_be_aggregate[None, :]

        return (1.0 - w_agg_matrix) * r_compact_cm[None, :] + w_agg_matrix * r_fractal

    if optics_mode == "aggregate_table":
        raise NotImplementedError(
            "aggregate_table is a planned mode. For now use compact_mie or "
            "aggregate_effective_mie."
        )

    raise ValueError(
        "optics_mode must be 'compact_mie', 'aggregate_effective_mie', "
        "or 'aggregate_table'."
    )


def compute_layer_optical_properties(
    result: dict[str, Any],
    refractive_index_file: str | Path,
    wavelength_um: np.ndarray | None = None,
    n_wavelength: int | None = None,
    wavelength_range_um: tuple[float, float] | None = None,
    optics_mode: str = "compact_mie",
    refrind_mapping: str = "auto",
    refrind_wave_unit: str = "auto",
    refrind_extrapolate: str = "clamp",
    verbose: bool = True,
) -> dict[str, Any]:
    """
    Compute layer optical properties from a finished Caligo result.

    Returns a dictionary containing optical-depth arrays on the Caligo
    microphysics grid.
    """
    if "ctx" not in result:
        raise KeyError("result must contain result['ctx'].")

    if "n" not in result:
        raise KeyError("result must contain result['n'].")

    ctx = result["ctx"]
    n_state = np.asarray(result["n"], dtype=float)

    Pbar = np.asarray(ctx["Pbar"], dtype=float)
    dz = np.asarray(ctx["dz"], dtype=float)
    n_bin = int(ctx["n_bin"])
    nz = int(ctx["nz"])

    if n_state.shape != (nz, n_bin):
        raise ValueError(
            "result['n'] has the wrong shape. "
            f"Got {n_state.shape}, expected {(nz, n_bin)}."
        )

    if dz.shape != (nz,):
        raise ValueError("ctx['dz'] must have shape (nz,).")

    refrind = read_refractive_index_file(
        refractive_index_file,
        mapping=refrind_mapping,
        wave_unit=refrind_wave_unit,
        verbose=verbose,
    )

    if wavelength_um is None:
        if wavelength_range_um is not None:
            lo, hi = wavelength_range_um
            if lo <= 0 or hi <= lo:
                raise ValueError("wavelength_range_um must be (positive_min, larger_max).")

            nwave = int(n_wavelength or 180)
            wavelength_um = np.logspace(np.log10(lo), np.log10(hi), nwave)
        elif n_wavelength is not None:
            wavelength_um = np.logspace(
                np.log10(float(refrind.wavelength_um.min())),
                np.log10(float(refrind.wavelength_um.max())),
                int(n_wavelength),
            )
        else:
            wavelength_um = refrind.wavelength_um.copy()
    else:
        wavelength_um = _as_array_1d(wavelength_um, "wavelength_um")

    wavelength_um = _as_array_1d(wavelength_um, "wavelength_um")

    if not np.all(wavelength_um > 0):
        raise ValueError("wavelength_um must be positive.")

    order_wave = np.argsort(wavelength_um)
    wavelength_um = wavelength_um[order_wave]

    m_solid_wave, refrind_diag = interpolate_refractive_index(
        refrind,
        wavelength_um,
        extrapolate=refrind_extrapolate,
    )

    radius_matrix_cm = _select_radius_matrix_cm(ctx, optics_mode)

    if radius_matrix_cm.shape != (nz, n_bin):
        raise ValueError("Internal radius matrix has the wrong shape.")

    rho_haze = float(ctx.get("rho_haze", 1.0))

    if optics_mode == "aggregate_effective_mie":
        rho_eff_layer = np.asarray(ctx["rho_eff_layer"], dtype=float)

        if rho_eff_layer.shape != (nz, n_bin):
            raise ValueError("ctx['rho_eff_layer'] must have shape (nz, n_bin).")

        filling_matrix = np.clip(rho_eff_layer / max(rho_haze, 1e-300), 0.0, 1.0)

        can_be_aggregate = np.asarray(
            ctx.get("can_be_aggregate", np.zeros(n_bin, dtype=bool)),
            dtype=bool,
        )

        w_agg_layer = np.asarray(ctx.get("w_agg_layer", np.zeros(nz)), dtype=float)
        w_agg_matrix = np.clip(w_agg_layer[:, None], 0.0, 1.0) * can_be_aggregate[None, :]
    else:
        filling_matrix = np.ones((nz, n_bin), dtype=float)
        w_agg_matrix = np.zeros((nz, n_bin), dtype=float)

    nwave = wavelength_um.size

    opd = np.zeros((nz, nwave), dtype=float)
    tau_sca = np.zeros((nz, nwave), dtype=float)
    g_num = np.zeros((nz, nwave), dtype=float)

    total_number_column_by_bin = np.sum(n_state * dz[:, None], axis=0)
    total_mass_column_by_bin = np.sum(
        n_state * np.asarray(ctx["m_bin"], dtype=float)[None, :] * dz[:, None],
        axis=0,
    )

    if verbose:
        r_min_nm = float(np.nanmin(radius_matrix_cm) * 1e7)
        r_max_nm = float(np.nanmax(radius_matrix_cm) * 1e7)
        print("Direct Caligo-grid Mie calculation")
        print("  optics_mode:", optics_mode)
        print("  layers:", nz)
        print("  bins:", n_bin)
        print("  wavelength points:", nwave)
        print("  wavelength range [um]:", float(wavelength_um.min()), "to", float(wavelength_um.max()))
        print("  optical radius range [nm]:", r_min_nm, "to", r_max_nm)

    for k in range(nz):
        number_column = n_state[k, :] * dz[k]

        if not np.any(number_column > 0):
            continue

        for i in range(n_bin):
            Ncol = float(number_column[i])

            if Ncol <= 0 or not np.isfinite(Ncol):
                continue

            radius_cm = float(radius_matrix_cm[k, i])

            if radius_cm <= 0 or not np.isfinite(radius_cm):
                continue

            radius_um = radius_cm * 1e4
            area_cm2 = np.pi * radius_cm**2

            if optics_mode == "aggregate_effective_mie":
                f_fill = float(filling_matrix[k, i])
                m_wave = _maxwell_garnett_effective_index(m_solid_wave, f_fill)
            else:
                m_wave = m_solid_wave

            for j, wave_um in enumerate(wavelength_um):
                qext, qsca, g = _mie_efficiencies_one(m_wave[j], radius_um, float(wave_um))

                if qext < 0 or qsca < 0:
                    continue

                qsca = min(qsca, qext) if qext > 0 else 0.0

                tau_ext_ij = Ncol * area_cm2 * qext
                tau_sca_ij = Ncol * area_cm2 * qsca

                opd[k, j] += tau_ext_ij
                tau_sca[k, j] += tau_sca_ij
                g_num[k, j] += tau_sca_ij * g

    w0 = np.zeros_like(opd)
    g0 = np.zeros_like(opd)

    positive_tau = opd > 0
    w0[positive_tau] = tau_sca[positive_tau] / opd[positive_tau]
    w0 = np.clip(w0, 0.0, 1.0)

    positive_sca = tau_sca > 0
    g0[positive_sca] = g_num[positive_sca] / tau_sca[positive_sca]
    g0 = np.clip(g0, -1.0, 1.0)

    wavenumber = 1e4 / wavelength_um

    vertical_tau = np.sum(opd, axis=0)

    diag = {
        "optics_mode": optics_mode,
        "n_layer_micro": int(nz),
        "n_bin": int(n_bin),
        "n_wavelength": int(nwave),
        "wavelength_min_um": float(wavelength_um.min()),
        "wavelength_max_um": float(wavelength_um.max()),
        "radius_min_nm": float(np.nanmin(radius_matrix_cm) * 1e7),
        "radius_max_nm": float(np.nanmax(radius_matrix_cm) * 1e7),
        "max_vertical_tau": float(np.nanmax(vertical_tau)),
        "min_vertical_tau": float(np.nanmin(vertical_tau)),
        "total_number_column_cm2": float(np.sum(total_number_column_by_bin)),
        "total_mass_column_g_cm2": float(np.sum(total_mass_column_by_bin)),
    }

    diag.update(refrind_diag)

    if optics_mode == "aggregate_effective_mie":
        diag.update(
            {
                "filling_factor_min": float(np.nanmin(filling_matrix)),
                "filling_factor_max": float(np.nanmax(filling_matrix)),
                "aggregate_weight_min": float(np.nanmin(w_agg_matrix)),
                "aggregate_weight_max": float(np.nanmax(w_agg_matrix)),
                "aggregate_effective_mie_note": (
                    "Porous-sphere Maxwell-Garnett approximation. "
                    "Not a full fractal-aggregate scattering calculation."
                ),
            }
        )

    if verbose:
        print("  vertical tau range:", float(np.nanmin(vertical_tau)), "to", float(np.nanmax(vertical_tau)))
        if diag["fraction_wavelength_outside_refrind"] > 0:
            print(
                "  warning: fraction of requested wavelengths outside refrind table:",
                diag["fraction_wavelength_outside_refrind"],
            )

    return {
        "ctx": ctx,
        "Pbar_micro": Pbar,
        "dz_micro": dz,
        "n_state": n_state,
        "wavelength_um": wavelength_um,
        "wavenumber": wavenumber,
        "opd_micro": opd,
        "w0_micro": w0,
        "g0_micro": g0,
        "vertical_tau": vertical_tau,
        "radius_matrix_cm": radius_matrix_cm,
        "diag": diag,
    }


# -----------------------------------------------------------------------------
# Photochem to PICASO atmosphere helpers
# -----------------------------------------------------------------------------


def find_photochem_object(case_like: Any) -> Any | None:
    """Find the photochem object cached by a Caligo case, if available."""
    photochem_result = getattr(case_like, "_photochem_result", None)

    if isinstance(photochem_result, dict):
        pc = photochem_result.get("pc")
        if pc is not None:
            return pc

    return None


def create_picaso_atmosphere_from_photochem(pc_object: Any) -> pd.DataFrame:
    """
    Export the final photochem atmosphere into a PICASO-ready dataframe.

    Photochem pressure is expected in dyn cm^-2. PICASO expects bar.
    Aerosol bookkeeping columns are skipped.
    """
    sol = pc_object.return_atmosphere()

    if "pressure" not in sol:
        raise KeyError("pc.return_atmosphere() did not return 'pressure'.")

    if "temperature" not in sol:
        raise KeyError("pc.return_atmosphere() did not return 'temperature'.")

    pressure_bar = np.asarray(sol["pressure"], dtype=float) / 1e6
    temperature = np.asarray(sol["temperature"], dtype=float)

    nlevel = pressure_bar.size

    atmosphere_data: dict[str, np.ndarray] = {
        "pressure": pressure_bar[::-1].copy(),
        "temperature": temperature[::-1].copy(),
    }

    for key, value in sol.items():
        if key in {"pressure", "temperature", "Kzz", "kzz", "KZZ"}:
            continue

        if "aer" in key.lower():
            continue

        arr = np.asarray(value, dtype=float)

        if arr.ndim != 1:
            continue

        if arr.size != nlevel:
            continue

        atmosphere_data[key] = arr[::-1].copy()

    atmosphere_df = pd.DataFrame(atmosphere_data)

    gas_columns = [
        col for col in atmosphere_df.columns if col not in {"pressure", "temperature"}
    ]

    if len(gas_columns) == 0:
        raise RuntimeError("No gas-abundance columns were exported from photochem.")

    return atmosphere_df


def _picaso_profile_dataframe(case_like: Any) -> pd.DataFrame | None:
    """Return the current PICASO atmosphere profile dataframe, if present."""
    try:
        profile = case_like.picaso.inputs["atmosphere"]["profile"]
    except Exception:
        return None

    if profile is None:
        return None

    if isinstance(profile, pd.DataFrame):
        return profile

    if hasattr(profile, "columns"):
        return pd.DataFrame(profile)

    if isinstance(profile, dict):
        return pd.DataFrame(profile)

    return None


def _profile_has_composition(profile: pd.DataFrame | None) -> bool:
    if profile is None:
        return False

    cols = set(profile.columns)

    if not {"pressure", "temperature"}.issubset(cols):
        return False

    gas_cols = [col for col in profile.columns if col not in {"pressure", "temperature", "kz", "Kzz", "kzz"}]

    return len(gas_cols) > 0


def attach_photochem_atmosphere_to_picaso(
    case_like: Any,
    pc_object: Any | None = None,
    verbose: bool = True,
) -> pd.DataFrame | None:
    """
    Attach the final photochem atmosphere to the wrapped PICASO case.

    If no photochem object is available but the current PICASO profile already
    has composition columns, the current profile is left unchanged.
    """
    if pc_object is None:
        pc_object = find_photochem_object(case_like)

    if pc_object is None:
        profile = _picaso_profile_dataframe(case_like)

        if _profile_has_composition(profile):
            if verbose:
                print("PICASO already has an atmosphere with composition columns.")
            return profile

        raise RuntimeError(
            "No photochem object was found, and the current PICASO atmosphere "
            "does not appear to contain gas abundances. Run case.run_photochem() "
            "first or pass pc_object explicitly."
        )

    atmosphere_df = create_picaso_atmosphere_from_photochem(pc_object)

    if verbose:
        gas_columns = [
            col for col in atmosphere_df.columns if col not in {"pressure", "temperature"}
        ]
        print("Attaching the final photochem atmosphere to PICASO.")
        print("  pressure levels:", len(atmosphere_df))
        print("  gas columns:", len(gas_columns))
        print("  first gas columns:", gas_columns[:15])

    case_like.atmosphere(atmosphere_df, verbose=False)

    return atmosphere_df


def picaso_layer_pressure_profile(case_like: Any) -> np.ndarray:
    """
    Return the PICASO cloud-layer pressure grid.

    PICASO stores atmospheres on pressure levels, while cloud tables need one
    value per layer, so there should be nlevel - 1 cloud pressures.
    """
    profile = _picaso_profile_dataframe(case_like)

    if profile is None or "pressure" not in profile.columns:
        raise RuntimeError("Could not find a PICASO pressure profile.")

    pressure_levels = np.asarray(profile["pressure"], dtype=float)
    expected_layers = int(case_like.picaso.nlevel) - 1

    if pressure_levels.size == expected_layers + 1:
        pressure_layers = pressure_levels[1:].copy()
    elif pressure_levels.size == expected_layers:
        pressure_layers = pressure_levels.copy()
    else:
        raise ValueError(
            "Unexpected PICASO pressure-grid size. "
            f"Found {pressure_levels.size}, expected {expected_layers + 1} "
            f"levels or {expected_layers} layers."
        )

    return pressure_layers


# -----------------------------------------------------------------------------
# Remapping and PICASO cloud-table formatting
# -----------------------------------------------------------------------------


def remap_layer_optics_by_log_pressure(
    Pbar_src: np.ndarray,
    opd_src: np.ndarray,
    w0_src: np.ndarray,
    g0_src: np.ndarray,
    Pbar_dst: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    """
    Conservatively remap layer optical properties between pressure grids.

    Optical depth is distributed by overlap in log-pressure space. Scattering
    optical depth and g-weighted scattering optical depth are remapped in the
    same way, then w0 and g0 are reconstructed.
    """
    Pbar_src = _as_array_1d(Pbar_src, "Pbar_src")
    Pbar_dst = _as_array_1d(Pbar_dst, "Pbar_dst")

    opd_src = np.asarray(opd_src, dtype=float)
    w0_src = np.asarray(w0_src, dtype=float)
    g0_src = np.asarray(g0_src, dtype=float)

    if opd_src.shape != w0_src.shape or opd_src.shape != g0_src.shape:
        raise ValueError("opd_src, w0_src, and g0_src must have the same shape.")

    if opd_src.shape[0] != Pbar_src.size:
        raise ValueError("opd_src first axis must match Pbar_src.")

    nwave = opd_src.shape[1]

    src_order = np.argsort(safe_log10(Pbar_src))
    dst_order = np.argsort(safe_log10(Pbar_dst))

    logP_src_sorted = safe_log10(Pbar_src[src_order])
    logP_dst_sorted = safe_log10(Pbar_dst[dst_order])

    src_faces = _faces_from_centers_ascending(logP_src_sorted)
    dst_faces = _faces_from_centers_ascending(logP_dst_sorted)

    opd_dst_sorted = np.zeros((Pbar_dst.size, nwave), dtype=float)
    sca_dst_sorted = np.zeros_like(opd_dst_sorted)
    gnum_dst_sorted = np.zeros_like(opd_dst_sorted)

    opd_src_sorted = opd_src[src_order, :]
    sca_src_sorted = opd_src_sorted * np.clip(w0_src[src_order, :], 0.0, 1.0)
    gnum_src_sorted = sca_src_sorted * np.clip(g0_src[src_order, :], -1.0, 1.0)

    source_tau_total = float(np.sum(opd_src_sorted))
    assigned_tau_total = 0.0

    j_start = 0

    for i in range(Pbar_src.size):
        left = src_faces[i]
        right = src_faces[i + 1]
        width = max(right - left, 1e-300)

        while j_start < Pbar_dst.size and dst_faces[j_start + 1] <= left:
            j_start += 1

        j = j_start

        while j < Pbar_dst.size and dst_faces[j] < right:
            overlap = max(0.0, min(right, dst_faces[j + 1]) - max(left, dst_faces[j]))

            if overlap > 0:
                frac = overlap / width
                opd_dst_sorted[j, :] += opd_src_sorted[i, :] * frac
                sca_dst_sorted[j, :] += sca_src_sorted[i, :] * frac
                gnum_dst_sorted[j, :] += gnum_src_sorted[i, :] * frac
                assigned_tau_total += float(np.sum(opd_src_sorted[i, :] * frac))

            j += 1

    w0_dst_sorted = np.zeros_like(opd_dst_sorted)
    g0_dst_sorted = np.zeros_like(opd_dst_sorted)

    positive_tau = opd_dst_sorted > 0
    w0_dst_sorted[positive_tau] = sca_dst_sorted[positive_tau] / opd_dst_sorted[positive_tau]
    w0_dst_sorted = np.clip(w0_dst_sorted, 0.0, 1.0)

    positive_sca = sca_dst_sorted > 0
    g0_dst_sorted[positive_sca] = gnum_dst_sorted[positive_sca] / sca_dst_sorted[positive_sca]
    g0_dst_sorted = np.clip(g0_dst_sorted, -1.0, 1.0)

    inv_dst_order = np.empty_like(dst_order)
    inv_dst_order[dst_order] = np.arange(dst_order.size)

    opd_dst = opd_dst_sorted[inv_dst_order, :]
    w0_dst = w0_dst_sorted[inv_dst_order, :]
    g0_dst = g0_dst_sorted[inv_dst_order, :]

    diag = {
        "source_tau_total_all_wavelengths": source_tau_total,
        "assigned_tau_total_all_wavelengths": float(assigned_tau_total),
        "lost_tau_fraction_all_wavelengths": float(
            max(source_tau_total - assigned_tau_total, 0.0)
            / max(source_tau_total, 1e-300)
        ),
    }

    return opd_dst, w0_dst, g0_dst, diag


def format_picaso_cloud_dataframe(
    opd: np.ndarray,
    w0: np.ndarray,
    g0: np.ndarray,
    pressure: np.ndarray,
    wavenumber: np.ndarray,
    use_virga_format: bool = False,
) -> pd.DataFrame:
    """Build a PICASO cloud dataframe from layer optical properties."""
    pressure = _as_array_1d(pressure, "pressure")
    wavenumber = _as_array_1d(wavenumber, "wavenumber")

    opd = np.asarray(opd, dtype=float)
    w0 = np.asarray(w0, dtype=float)
    g0 = np.asarray(g0, dtype=float)

    expected_shape = (pressure.size, wavenumber.size)

    if opd.shape != expected_shape:
        raise ValueError(f"opd shape {opd.shape} does not match {expected_shape}.")

    if w0.shape != expected_shape or g0.shape != expected_shape:
        raise ValueError("w0 and g0 must match opd shape.")

    if use_virga_format:
        try:
            from virga import justdoit as vdi  # type: ignore
        except Exception as exc:
            raise ImportError(
                "use_virga_format=True requires virga. Set use_virga_format=False "
                "to use Caligo's local dataframe formatter."
            ) from exc

        return vdi.picaso_format(
            opd,
            w0,
            g0,
            pressure=pressure,
            wavenumber=wavenumber,
        )

    rows = []

    for k, p in enumerate(pressure):
        for j, wno in enumerate(wavenumber):
            rows.append(
                {
                    "pressure": float(p),
                    "wavenumber": float(wno),
                    "opd": float(max(opd[k, j], 0.0)),
                    "w0": float(np.clip(w0[k, j], 0.0, 1.0)),
                    "g0": float(np.clip(g0[k, j], -1.0, 1.0)),
                }
            )

    return pd.DataFrame(rows, columns=["pressure", "wavenumber", "opd", "w0", "g0"])


def build_picaso_cloud_from_caligo(
    result: dict[str, Any],
    case: Any,
    refractive_index_file: str | Path,
    wavelength_um: np.ndarray | None = None,
    n_wavelength: int | None = None,
    wavelength_range_um: tuple[float, float] | None = None,
    optics_mode: str = "compact_mie",
    attach_photochem_atmosphere: bool = True,
    pc_object: Any | None = None,
    refrind_mapping: str = "auto",
    refrind_wave_unit: str = "auto",
    refrind_extrapolate: str = "clamp",
    use_virga_format: bool = False,
    verbose: bool = True,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """
    Build a PICASO cloud table from a finished Caligo microphysics result.

    This is the main user-facing function for Caligo to PICASO post-processing.
    """
    atmosphere_df = None

    if attach_photochem_atmosphere:
        atmosphere_df = attach_photochem_atmosphere_to_picaso(
            case,
            pc_object=pc_object,
            verbose=verbose,
        )

    Pbar_picaso = picaso_layer_pressure_profile(case)

    optics = compute_layer_optical_properties(
        result=result,
        refractive_index_file=refractive_index_file,
        wavelength_um=wavelength_um,
        n_wavelength=n_wavelength,
        wavelength_range_um=wavelength_range_um,
        optics_mode=optics_mode,
        refrind_mapping=refrind_mapping,
        refrind_wave_unit=refrind_wave_unit,
        refrind_extrapolate=refrind_extrapolate,
        verbose=verbose,
    )

    opd_picaso, w0_picaso, g0_picaso, remap_diag = remap_layer_optics_by_log_pressure(
        optics["Pbar_micro"],
        optics["opd_micro"],
        optics["w0_micro"],
        optics["g0_micro"],
        Pbar_picaso,
    )

    cloud_df = format_picaso_cloud_dataframe(
        opd_picaso,
        w0_picaso,
        g0_picaso,
        pressure=Pbar_picaso,
        wavenumber=optics["wavenumber"],
        use_virga_format=use_virga_format,
    )

    expected_rows = len(Pbar_picaso) * len(optics["wavenumber"])

    if len(cloud_df) != expected_rows:
        raise RuntimeError(
            "PICASO cloud table has the wrong number of rows. "
            f"Got {len(cloud_df)}, expected {expected_rows}."
        )

    diag = dict(optics["diag"])
    diag.update(remap_diag)
    diag.update(
        {
            "picaso_cloud_layers": int(len(Pbar_picaso)),
            "picaso_cloud_rows": int(len(cloud_df)),
            "picaso_cloud_expected_rows": int(expected_rows),
            "use_virga_format": bool(use_virga_format),
        }
    )

    if atmosphere_df is not None:
        diag["picaso_atmosphere_levels"] = int(len(atmosphere_df))
        diag["picaso_atmosphere_columns"] = list(atmosphere_df.columns)

    out = {
        "cloud_df": cloud_df,
        "atmosphere_df": atmosphere_df,
        "Pbar_picaso": Pbar_picaso,
        "opd_picaso": opd_picaso,
        "w0_picaso": w0_picaso,
        "g0_picaso": g0_picaso,
        "wavelength_um": optics["wavelength_um"],
        "wavenumber": optics["wavenumber"],
        "vertical_tau_micro": optics["vertical_tau"],
        "optics": optics,
        "diag": diag,
    }

    if verbose:
        print("PICASO cloud table built.")
        print("  layers:", diag["picaso_cloud_layers"])
        print("  wavelengths:", diag["n_wavelength"])
        print("  rows:", diag["picaso_cloud_rows"])
        print("  lost tau fraction in pressure remap:", diag["lost_tau_fraction_all_wavelengths"])

    return cloud_df, out


# -----------------------------------------------------------------------------
# Spectrum helper
# -----------------------------------------------------------------------------


def run_clear_and_hazy_transmission(
    case: Any,
    opacity_ck: Any,
    cloud_df: pd.DataFrame,
    calculation: str = "transmission",
    full_output: bool = True,
) -> dict[str, Any]:
    """Run clear and hazy PICASO transmission spectra for one cloud table."""
    clear_cloud_df = cloud_df.copy()
    clear_cloud_df["opd"] = 0.0

    case.clouds(df=clear_cloud_df)
    clear = case.spectrum(opacity_ck, calculation=calculation, full_output=full_output)

    case.clouds(df=cloud_df)
    hazy = case.spectrum(opacity_ck, calculation=calculation, full_output=full_output)

    required = {"wavenumber", "transit_depth"}

    for label, spectrum in [("clear", clear), ("hazy", hazy)]:
        missing = required - set(spectrum.keys())
        if missing:
            raise KeyError(
                f"The {label} PICASO spectrum is missing keys {sorted(missing)}. "
                f"Available keys: {list(spectrum.keys())}"
            )

    wno_clear = np.asarray(clear["wavenumber"], dtype=float)
    td_clear = np.asarray(clear["transit_depth"], dtype=float)
    wno_hazy = np.asarray(hazy["wavenumber"], dtype=float)
    td_hazy = np.asarray(hazy["transit_depth"], dtype=float)

    wave_clear_um = 1e4 / wno_clear
    wave_hazy_um = 1e4 / wno_hazy

    order_clear = np.argsort(wave_clear_um)
    order_hazy = np.argsort(wave_hazy_um)

    wave_clear_um = wave_clear_um[order_clear]
    td_clear = td_clear[order_clear]
    wave_hazy_um = wave_hazy_um[order_hazy]
    td_hazy = td_hazy[order_hazy]

    clear_interp = np.interp(wave_hazy_um, wave_clear_um, td_clear)
    delta = td_hazy - clear_interp

    return {
        "clear": clear,
        "hazy": hazy,
        "wavelength_clear_um": wave_clear_um,
        "transit_depth_clear": td_clear,
        "wavelength_hazy_um": wave_hazy_um,
        "transit_depth_hazy": td_hazy,
        "transit_depth_clear_interp": clear_interp,
        "haze_minus_clear": delta,
        "transit_depth_clear_ppm": td_clear * 1e6,
        "transit_depth_hazy_ppm": td_hazy * 1e6,
        "haze_minus_clear_ppm": delta * 1e6,
    }



# -----------------------------------------------------------------------------
# Bin-level optical diagnostics and compact/aggregate comparisons
# -----------------------------------------------------------------------------


def compute_tau_contribution_by_bin(
    result: dict[str, Any],
    refractive_index_file: str | Path,
    wavelength_um: np.ndarray | None = None,
    n_wavelength: int | None = None,
    wavelength_range_um: tuple[float, float] | None = None,
    optics_mode: str = "compact_mie",
    refrind_mapping: str = "auto",
    refrind_wave_unit: str = "auto",
    refrind_extrapolate: str = "clamp",
    verbose: bool = True,
) -> dict[str, Any]:
    """
    Compute the vertical optical-depth contribution from each particle bin.

    This diagnostic recomputes the direct-Mie opacity on the Caligo grid, but
    keeps the contribution from each particle-size bin separate. It is meant
    to answer questions like:

        Which bins dominate the haze optical depth?
        Are very large porous aggregate radii controlling the spectrum?
        Does compact_mie or aggregate_effective_mie shift opacity into
        different particle sizes?

    Returns
    -------
    dict
        Contains wavelength_um, vertical_tau, tau_by_bin, bin-level fractions,
        number and mass columns, and a representative optical radius for each
        bin.
    """
    if "ctx" not in result:
        raise KeyError("result must contain result['ctx'].")

    if "n" not in result:
        raise KeyError("result must contain result['n'].")

    ctx = result["ctx"]
    n_state = np.asarray(result["n"], dtype=float)

    Pbar = np.asarray(ctx["Pbar"], dtype=float)
    dz = np.asarray(ctx["dz"], dtype=float)
    n_bin = int(ctx["n_bin"])
    nz = int(ctx["nz"])

    if n_state.shape != (nz, n_bin):
        raise ValueError(
            "result['n'] has the wrong shape. "
            f"Got {n_state.shape}, expected {(nz, n_bin)}."
        )

    if dz.shape != (nz,):
        raise ValueError("ctx['dz'] must have shape (nz,).")

    refrind = read_refractive_index_file(
        refractive_index_file,
        mapping=refrind_mapping,
        wave_unit=refrind_wave_unit,
        verbose=verbose,
    )

    if wavelength_um is None:
        if wavelength_range_um is not None:
            lo, hi = wavelength_range_um
            if lo <= 0 or hi <= lo:
                raise ValueError("wavelength_range_um must be (positive_min, larger_max).")

            nwave = int(n_wavelength or 180)
            wavelength_um = np.logspace(np.log10(lo), np.log10(hi), nwave)

        elif n_wavelength is not None:
            wavelength_um = np.logspace(
                np.log10(float(refrind.wavelength_um.min())),
                np.log10(float(refrind.wavelength_um.max())),
                int(n_wavelength),
            )

        else:
            wavelength_um = refrind.wavelength_um.copy()

    else:
        wavelength_um = _as_array_1d(wavelength_um, "wavelength_um")

    wavelength_um = _as_array_1d(wavelength_um, "wavelength_um")

    if not np.all(wavelength_um > 0):
        raise ValueError("wavelength_um must be positive.")

    order_wave = np.argsort(wavelength_um)
    wavelength_um = wavelength_um[order_wave]

    m_solid_wave, refrind_diag = interpolate_refractive_index(
        refrind,
        wavelength_um,
        extrapolate=refrind_extrapolate,
    )

    radius_matrix_cm = _select_radius_matrix_cm(ctx, optics_mode)

    if radius_matrix_cm.shape != (nz, n_bin):
        raise ValueError("Internal radius matrix has the wrong shape.")

    rho_haze = float(ctx.get("rho_haze", 1.0))

    if optics_mode == "aggregate_effective_mie":
        rho_eff_layer = np.asarray(ctx["rho_eff_layer"], dtype=float)

        if rho_eff_layer.shape != (nz, n_bin):
            raise ValueError("ctx['rho_eff_layer'] must have shape (nz, n_bin).")

        filling_matrix = np.clip(rho_eff_layer / max(rho_haze, 1e-300), 0.0, 1.0)

        can_be_aggregate = np.asarray(
            ctx.get("can_be_aggregate", np.zeros(n_bin, dtype=bool)),
            dtype=bool,
        )

        w_agg_layer = np.asarray(ctx.get("w_agg_layer", np.zeros(nz)), dtype=float)
        w_agg_matrix = np.clip(w_agg_layer[:, None], 0.0, 1.0) * can_be_aggregate[None, :]

    else:
        filling_matrix = np.ones((nz, n_bin), dtype=float)
        w_agg_matrix = np.zeros((nz, n_bin), dtype=float)

    nwave = wavelength_um.size

    tau_by_bin = np.zeros((n_bin, nwave), dtype=float)
    tau_by_layer_bin = np.zeros((nz, n_bin, nwave), dtype=float)

    number_column_by_layer_bin = n_state * dz[:, None]
    number_column_by_bin = np.sum(number_column_by_layer_bin, axis=0)

    m_bin = np.asarray(ctx["m_bin"], dtype=float)
    mass_column_by_bin = np.sum(n_state * m_bin[None, :] * dz[:, None], axis=0)

    # Representative radius per bin, weighted by particle number column.
    radius_nm_matrix = radius_matrix_cm * 1e7
    radius_nm_by_bin = np.zeros(n_bin, dtype=float)

    for i in range(n_bin):
        weights = number_column_by_layer_bin[:, i]

        if np.sum(weights) > 0:
            radius_nm_by_bin[i] = float(
                np.sum(radius_nm_matrix[:, i] * weights)
                / np.maximum(np.sum(weights), 1e-300)
            )
        else:
            radius_nm_by_bin[i] = float(np.nanmedian(radius_nm_matrix[:, i]))

    compact_radius_nm = np.asarray(ctx["r_compact_nm"], dtype=float)

    if verbose:
        print("Bin-level direct-Mie optical-depth diagnostic")
        print("  optics_mode:", optics_mode)
        print("  layers:", nz)
        print("  bins:", n_bin)
        print("  wavelength points:", nwave)
        print("  wavelength range [um]:", float(wavelength_um.min()), "to", float(wavelength_um.max()))
        print("  representative optical radius range [nm]:",
              float(np.nanmin(radius_nm_by_bin)), "to", float(np.nanmax(radius_nm_by_bin)))

    for k in range(nz):
        for i in range(n_bin):
            Ncol = float(number_column_by_layer_bin[k, i])

            if Ncol <= 0 or not np.isfinite(Ncol):
                continue

            radius_cm = float(radius_matrix_cm[k, i])

            if radius_cm <= 0 or not np.isfinite(radius_cm):
                continue

            radius_um = radius_cm * 1e4
            area_cm2 = np.pi * radius_cm**2

            if optics_mode == "aggregate_effective_mie":
                f_fill = float(filling_matrix[k, i])
                m_wave = _maxwell_garnett_effective_index(m_solid_wave, f_fill)
            else:
                m_wave = m_solid_wave

            for j, wave_um in enumerate(wavelength_um):
                qext, _qsca, _g = _mie_efficiencies_one(m_wave[j], radius_um, float(wave_um))

                if qext <= 0 or not np.isfinite(qext):
                    continue

                tau = Ncol * area_cm2 * qext
                tau_by_layer_bin[k, i, j] = tau
                tau_by_bin[i, j] += tau

    vertical_tau = np.sum(tau_by_bin, axis=0)

    if np.any(vertical_tau > 0):
        peak_index = int(np.nanargmax(vertical_tau))
    else:
        peak_index = 0

    tau_by_bin_at_peak = tau_by_bin[:, peak_index]
    total_peak_tau = float(np.sum(tau_by_bin_at_peak))

    tau_fraction_by_bin_at_peak = (
        tau_by_bin_at_peak
        / np.maximum(total_peak_tau, 1e-300)
    )

    # Integrate over log wavelength so the diagnostic is less sensitive to
    # uneven wavelength spacing.
    log_wave = np.log(np.maximum(wavelength_um, 1e-300))

    if nwave > 1:
        tau_by_bin_integrated = np.trapz(tau_by_bin, x=log_wave, axis=1)
    else:
        tau_by_bin_integrated = tau_by_bin[:, 0].copy()

    tau_by_bin_integrated = np.maximum(tau_by_bin_integrated, 0.0)
    total_integrated_tau = float(np.sum(tau_by_bin_integrated))

    tau_fraction_by_bin_integrated = (
        tau_by_bin_integrated
        / np.maximum(total_integrated_tau, 1e-300)
    )

    giant_radius_mask = radius_nm_by_bin > 1.0e4

    diag = {
        "optics_mode": optics_mode,
        "n_layer_micro": int(nz),
        "n_bin": int(n_bin),
        "n_wavelength": int(nwave),
        "wavelength_min_um": float(wavelength_um.min()),
        "wavelength_max_um": float(wavelength_um.max()),
        "peak_wavelength_um": float(wavelength_um[peak_index]),
        "max_vertical_tau": float(np.nanmax(vertical_tau)),
        "total_peak_tau": float(total_peak_tau),
        "total_integrated_tau_logwave": float(total_integrated_tau),
        "representative_radius_min_nm": float(np.nanmin(radius_nm_by_bin)),
        "representative_radius_max_nm": float(np.nanmax(radius_nm_by_bin)),
        "fraction_peak_tau_radius_gt_10000_nm": float(
            np.sum(tau_fraction_by_bin_at_peak[giant_radius_mask])
        ),
        "fraction_integrated_tau_radius_gt_10000_nm": float(
            np.sum(tau_fraction_by_bin_integrated[giant_radius_mask])
        ),
        "total_number_column_cm2": float(np.sum(number_column_by_bin)),
        "total_mass_column_g_cm2": float(np.sum(mass_column_by_bin)),
    }

    diag.update(refrind_diag)

    if optics_mode == "aggregate_effective_mie":
        diag.update(
            {
                "filling_factor_min": float(np.nanmin(filling_matrix)),
                "filling_factor_max": float(np.nanmax(filling_matrix)),
                "aggregate_weight_min": float(np.nanmin(w_agg_matrix)),
                "aggregate_weight_max": float(np.nanmax(w_agg_matrix)),
                "aggregate_effective_mie_note": (
                    "Porous-sphere Maxwell-Garnett approximation. "
                    "Not a full fractal-aggregate scattering calculation."
                ),
            }
        )

    if verbose:
        print("  max vertical tau:", diag["max_vertical_tau"])
        print("  peak wavelength [um]:", diag["peak_wavelength_um"])
        print(
            "  fraction of peak tau from representative radius > 10,000 nm:",
            diag["fraction_peak_tau_radius_gt_10000_nm"],
        )
        print(
            "  fraction of integrated tau from representative radius > 10,000 nm:",
            diag["fraction_integrated_tau_radius_gt_10000_nm"],
        )

    return {
        "ctx": ctx,
        "Pbar_micro": Pbar,
        "dz_micro": dz,
        "n_state": n_state,
        "wavelength_um": wavelength_um,
        "wavenumber": 1e4 / wavelength_um,
        "tau_by_bin": tau_by_bin,
        "tau_by_layer_bin": tau_by_layer_bin,
        "vertical_tau": vertical_tau,
        "peak_index": peak_index,
        "peak_wavelength_um": float(wavelength_um[peak_index]),
        "tau_by_bin_at_peak": tau_by_bin_at_peak,
        "tau_fraction_by_bin_at_peak": tau_fraction_by_bin_at_peak,
        "tau_by_bin_integrated": tau_by_bin_integrated,
        "tau_fraction_by_bin_integrated": tau_fraction_by_bin_integrated,
        "compact_radius_nm": compact_radius_nm,
        "radius_nm_by_bin": radius_nm_by_bin,
        "number_column_by_bin": number_column_by_bin,
        "mass_column_by_bin": mass_column_by_bin,
        "radius_matrix_cm": radius_matrix_cm,
        "diag": diag,
    }


def compare_compact_and_aggregate_optics(
    result: dict[str, Any],
    refractive_index_file: str | Path,
    wavelength_um: np.ndarray | None = None,
    n_wavelength: int | None = None,
    wavelength_range_um: tuple[float, float] | None = None,
    refrind_mapping: str = "auto",
    refrind_wave_unit: str = "auto",
    refrind_extrapolate: str = "clamp",
    verbose: bool = True,
) -> dict[str, Any]:
    """
    Compare compact_mie and aggregate_effective_mie on the same Caligo result.

    This uses the same wavelength grid for both calculations and returns the
    vertical optical depths and aggregate/compact ratio.
    """
    compact = compute_layer_optical_properties(
        result=result,
        refractive_index_file=refractive_index_file,
        wavelength_um=wavelength_um,
        n_wavelength=n_wavelength,
        wavelength_range_um=wavelength_range_um,
        optics_mode="compact_mie",
        refrind_mapping=refrind_mapping,
        refrind_wave_unit=refrind_wave_unit,
        refrind_extrapolate=refrind_extrapolate,
        verbose=verbose,
    )

    aggregate = compute_layer_optical_properties(
        result=result,
        refractive_index_file=refractive_index_file,
        wavelength_um=compact["wavelength_um"],
        optics_mode="aggregate_effective_mie",
        refrind_mapping=refrind_mapping,
        refrind_wave_unit=refrind_wave_unit,
        refrind_extrapolate=refrind_extrapolate,
        verbose=verbose,
    )

    wave = compact["wavelength_um"]
    tau_compact = compact["vertical_tau"]
    tau_aggregate = aggregate["vertical_tau"]

    ratio = tau_aggregate / np.maximum(tau_compact, 1e-300)

    if wave.size > 1:
        int_compact = float(np.trapz(tau_compact, x=np.log(wave)))
        int_aggregate = float(np.trapz(tau_aggregate, x=np.log(wave)))
    else:
        int_compact = float(tau_compact[0])
        int_aggregate = float(tau_aggregate[0])

    peak_compact_idx = int(np.nanargmax(tau_compact)) if np.any(tau_compact > 0) else 0
    peak_aggregate_idx = int(np.nanargmax(tau_aggregate)) if np.any(tau_aggregate > 0) else 0

    diag = {
        "max_tau_compact": float(np.nanmax(tau_compact)),
        "max_tau_aggregate_effective": float(np.nanmax(tau_aggregate)),
        "peak_wavelength_compact_um": float(wave[peak_compact_idx]),
        "peak_wavelength_aggregate_effective_um": float(wave[peak_aggregate_idx]),
        "integrated_tau_compact_logwave": float(max(int_compact, 0.0)),
        "integrated_tau_aggregate_effective_logwave": float(max(int_aggregate, 0.0)),
        "integrated_tau_ratio_aggregate_over_compact": float(
            max(int_aggregate, 0.0) / max(max(int_compact, 0.0), 1e-300)
        ),
        "max_ratio_aggregate_over_compact": float(np.nanmax(ratio)),
        "min_ratio_aggregate_over_compact": float(np.nanmin(ratio)),
        "median_ratio_aggregate_over_compact": float(np.nanmedian(ratio)),
    }

    if verbose:
        print("Compact vs aggregate-effective optics comparison")
        for key, value in diag.items():
            print(f"  {key}: {value}")

    return {
        "compact": compact,
        "aggregate_effective": aggregate,
        "wavelength_um": wave,
        "tau_compact": tau_compact,
        "tau_aggregate_effective": tau_aggregate,
        "ratio_aggregate_over_compact": ratio,
        "diag": diag,
    }


def plot_compact_vs_aggregate_tau(
    comparison: dict[str, Any],
    ax: Any | None = None,
) -> Any:
    """
    Plot compact and aggregate-effective vertical haze optical depths.

    Returns the matplotlib axis.
    """
    import matplotlib.pyplot as plt

    if ax is None:
        _, ax = plt.subplots(figsize=(7.6, 4.8))

    wave = np.asarray(comparison["wavelength_um"], dtype=float)
    tau_compact = np.asarray(comparison["tau_compact"], dtype=float)
    tau_aggregate = np.asarray(comparison["tau_aggregate_effective"], dtype=float)

    ax.loglog(
        wave,
        np.maximum(tau_compact, 1e-300),
        label="compact Mie",
    )

    ax.loglog(
        wave,
        np.maximum(tau_aggregate, 1e-300),
        label="aggregate effective Mie",
    )

    ax.set_xlabel("Wavelength [µm]")
    ax.set_ylabel("Vertical haze optical depth")
    ax.set_title("Compact vs aggregate-effective haze opacity")
    ax.legend()
    ax.grid(alpha=0.3, which="both")

    return ax


def plot_compact_vs_aggregate_ratio(
    comparison: dict[str, Any],
    ax: Any | None = None,
) -> Any:
    """
    Plot aggregate-effective optical depth divided by compact optical depth.

    Returns the matplotlib axis.
    """
    import matplotlib.pyplot as plt

    if ax is None:
        _, ax = plt.subplots(figsize=(7.6, 4.2))

    wave = np.asarray(comparison["wavelength_um"], dtype=float)
    ratio = np.asarray(comparison["ratio_aggregate_over_compact"], dtype=float)

    ax.semilogx(
        wave,
        ratio,
    )

    ax.axhline(
        1.0,
        linewidth=1,
    )

    ax.set_xlabel("Wavelength [µm]")
    ax.set_ylabel("Aggregate effective / compact")
    ax.set_title("Aggregate-effective opacity ratio")
    ax.grid(alpha=0.3, which="both")

    return ax

